#!/bin/sh

lock() {
  # Iniciando o processo de bloqueio de tela
  /opt/scripts/i3lock/lockscreen.sh &
  # Enquanto o bloqueio de tela não for executado não executa o commando suspender/hibernar
  while :; do
    if [[ $(xdotool search -sync -all -onlyvisible --name i3lock) ]]; then
      $@
      exit
    fi
  done
}

case "$1" in
    lock)
      lock `sleep 1 && xset dpms force off`
        ;;
    logout)
        i3-msg exit
        ;;
    switch_user)
	dm-tool switch-to-greeter
	;;
    suspend)
	if [ $(cat /proc/1/comm) = "systemd" ]; then 
	lock systemctl suspend

	else
	  lock dbus-send --system --print-reply --type=method_call --reply-timeout=2000 --dest=org.freedesktop.UPower /org/freedesktop/UPower org.freedesktop.UPower.Suspend
	fi
        ;;
    hibernate)
	if [ $(cat /proc/1/comm) = "systemd" ]; then
	lock systemctl hibernate
	else
	lock dbus-send --system --print-reply --type=method_call --reply-timeout=2000 --dest=org.freedesktop.UPower /org/freedesktop/UPower org.freedesktop.UPower.Hibernate
	fi
        ;;
    reboot)
	if [ $(cat /proc/1/comm) = "systemd" ]; then
        systemctl reboot
	else
	dbus-send --system --print-reply --type=method_call --reply-timeout=2000 --dest=org.freedesktop.ConsoleKit /org/freedesktop/ConsoleKit/Manager org.freedesktop.ConsoleKit.Manager.Restart
	fi
        ;;
    shutdown)
	if [ $(cat /proc/1/comm) = "systemd" ]; then
        systemctl poweroff
        else
	dbus-send --system --print-reply --type=method_call --reply-timeout=2000 --dest=org.freedesktop.ConsoleKit /org/freedesktop/ConsoleKit/Manager org.freedesktop.ConsoleKit.Manager.Stop
	fi
	;;
    *)
        echo "Usage: $0 {lock|logout|switch_user|suspend|hibernate|reboot|shutdown}"
        exit 2
esac

exit 0
