#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...

xrdb ~/.Xresources

man() {
    env LESS_TERMCAP_mb=$'\E[01;31m' \
    LESS_TERMCAP_md=$'\E[01;38;5;74m' \
    LESS_TERMCAP_me=$'\E[0m' \
    LESS_TERMCAP_se=$'\E[0m' \
    LESS_TERMCAP_so=$'\E[38;5;246m' \
    LESS_TERMCAP_ue=$'\E[0m' \
    LESS_TERMCAP_us=$'\E[04;38;5;146m' \
    man "$@"
}

# vim superman
vman() {
  vim -c "SuperMan $*"

  if [ "$?" != "0" ]; then
    echo "No manual entry for $*"
  fi
}

# man autocomplete > vman
# compdef vman="man"

stty -ixon

export GOPATH=~/go
export PATH=$PATH:$GOPATH/bin
export PATH=$PATH:/usr/lib/eclipse/

PATH="/home/rafael/perl5/bin${PATH+:}${PATH}"; export PATH;
PERL5LIB="/home/rafael/perl5/lib/perl5${PERL5LIB+:}${PERL5LIB}"; export PERL5LIB;
PERL_LOCAL_LIB_ROOT="/home/rafael/perl5${PERL_LOCAL_LIB_ROOT+:}${PERL_LOCAL_LIB_ROOT}"; export PERL_LOCAL_LIB_ROOT;
PERL_MB_OPT="--install_base \"/home/rafael/perl5\""; export PERL_MB_OPT;
PERL_MM_OPT="INSTALL_BASE=/home/rafael/perl5"; export PERL_MM_OPT;

alias CMD_HOTSPOT="_ create_ap wlo1 enp8s0 ZueraADS ads123456"
alias ultimo_arquivo="ls -t | head -1"
alias pkg-update='sudo etckeeper pre-install && yaourt -Suya && sudo etckeeper post-install'
alias CMD_ENVIAR_PHONE="/opt/scripts/kdeconnect-send"
alias extract="aunpack"
alias clipboard='xclip -sel clip'
export EDITOR="nvim"
export BROWSER="firefox"
export LIBVA_DRIVER_NAME=vdpau
alias note='nvim "/home/rafael/Documentos/Notes/$(ls ~/Documentos/Notes/ | fzf)"'

source ~/.fzf.zsh
export FZF_DEFAULT_COMMAND='ag -g ""'
export FZF_DEFAULT_OPTS="-i"
export FZF_COMPLETION_TRIGGER='--'

ulimit -n 2048

setopt HIST_FIND_NO_DUPS
setopt HIST_IGNORE_ALL_DUPS
setopt HIST_EXPIRE_DUPS_FIRST

eval `dircolors ~/dircolors.default`

source ~/.zsh/plugins/alias-tips/alias-tips.plugin.zsh
# source ~/.bin/tmuxinator.zsh
export ZSH_PLUGINS_ALIAS_TIPS_TEXT="Dica: "

# fpath=(~/.zsh/completions $fpath)
# autoload -Uz compinit && compinit -i
