#!/bin/bash

TAG_FILE="$PWD/tags"
echo $TAG_FILE
echo $PWD

/usr/bin/ctags --recurse --tag-relative \
  --languages=-javascript,sql \
  --exclude=.git \
  --sort=yes --append \
  --PHP-kinds=+cf \
  --regex-PHP='/abstract class ([^ ]*)/\1/c/' \
  --regex-PHP='/interface ([^ ]*)/\1/c/' \
  --regex-PHP='/(public |static |abstract |protected |private )+function ([^ (]*)/\2/f/' \
  -f "${TAG_FILE}" \
