#!/bin/bash

# Executar VLC
# vlc --qt-minimal-view --no-fullscreen $1&
PLAYER=mpv

if [ -z $1 ]; then
  VIDEO=$(yad --title "Insira o Vídeo do Youtube:" --entry --text "" --width=300 --center --button="gtk-cancel:252" --button="gtk-ok:0")
else
 VIDEO=$1
fi

if [ -z $VIDEO ]; then
  notify-send "Floating Vídeo" "Vídeo não encontrado."
  exit
fi

$PLAYER --ytdl --ytdl-format="best[height<=720]" "$VIDEO" &
notify-send "Floating Vídeo" "Abrindo Vídeo..."


# Esperar o Player abrir para reduzir o tamanho da janela
while :; do
  if [[ $(xdotool search -sync -all -onlyvisible --class $PLAYER) ]]; then
    # Modificar a janela do SMPlayer para floating
    # Mudar o tamanho da janela e mover para o canto do monitor

    i3-msg "[class=\"$PLAYER\"] floating enable, sticky enable, resize set 400 200, move position 960 560"
    exit
  fi
  sleep 0.5
done
