#!/bin/sh
xbacklight $1 $2 &

brightness=`xbacklight`
brilho_int=`expr $brightness`
volnoti-show -s /usr/share/pixmaps/volnoti/display-brightness-symbolic.svg $brilho_int &
# notify-send " " -i notification-display-brightness-low -h int:value:$brilho_int -h string:x-canonical-private-synchronous:brightness &
