#!/usr/bin/env bash
linguagem_origem="auto"
linguagem_alvo="pt-br"
text="$(xsel -o)"
translate="$(wget -U "Mozilla/5.0" -qO - "http://translate.googleapis.com/translate_a/single?client=gtx&sl=$linguagem_origem&tl=$linguagem_alvo&dt=t&q=$(echo $text | sed "s/[\"'<>]//g")" | sed "s/,,,0]],,.*//g" | awk -F'"' '{print $2, $6}')"
echo -e "Texto Original:" "$text"'\n' > /tmp/notitrans
echo "Tradução:" "$translate" >> /tmp/notitrans
yad --text-info --title="Translation" --wrap --filename=/tmp/notitrans
