#!/bin/bash
IF=$BLOCK_INSTANCE
# echo "teste"
# echo "teste"

if [ -z "$IF" ]; then
  IF=`ls -1 /sys/class/net/ | head -1`
fi
  RXPREV=-1
  TXPREV=-1
  while [ 1 == 1 ] ; do
    RX=`cat /sys/class/net/${IF}/statistics/rx_bytes`
    TX=`cat /sys/class/net/${IF}/statistics/tx_bytes`
    if [ $RXPREV -ne -1 ] ; then
      BWRX=$((($RX-$RXPREV)/1024))
      BWTX=$((($TX-$TXPREV)/1024))
      echo ": $BWRX KB/s : $BWTX KB/s"
      echo ": $BWRX KB/s : $BWTX KB/s"
    fi
    RXPREV=$RX
    TXPREV=$TX
    sleep 1
  done
